version: '3.8'

services:
  db:
    image: postgres:16.0
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
    expose:
      - 5432
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 backend_project.wsgi
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    expose:
    - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx: 
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:

